// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventsExpress.Db.Migrations
{
    public partial class UpdateNotificationTemplates : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "Message", "Subject", "Title" },
                values: new object[,]
                {
                    { 1, "Dear {{UserEmail}}, your account was blocked for some reason!", "Your account was blocked", "BlockedUser" },
                    { 2, "Follow the <a href='{{EventScheduleLink}}'>link</a> to create the recurrent event.", "Approve your recurrent event!", "CreateEventVerification" },
                    { 3, "For confirm your email please follow the <a href='{{EmailLink}}'>link</a>", "EventExpress registration", "RegisterVerification" },
                    { 4, "Dear {{UserEmail}}, congratulations, your account was Unblocked, so you can come back and enjoy spending your time in EventsExpress", "Your account was Unblocked", "UnblockedUser" },
                    { 5, "Dear {{UserEmail}}, your <a href='{{EventLink}}'>event</a> has been changed.", "Your event was changed", "OwnEventChanged" },
                    { 6, "Dear {{UserEmail}}, your joined <a href='{{EventLink}}'>event</a> has been changed.", "Joined event was changed", "JoinedEventChanged" }
                });

            migrationBuilder.UpdateData(
                table: "NotificationTypes",
                keyColumn: "Id",
                keyValue: 1,
                column: "Name",
                value: "User Status Change");

            migrationBuilder.UpdateData(
                table: "NotificationTypes",
                keyColumn: "Id",
                keyValue: 3,
                column: "Name",
                value: "Joined Event Change");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.UpdateData(
                table: "NotificationTypes",
                keyColumn: "Id",
                keyValue: 1,
                column: "Name",
                value: "Profile Change");

            migrationBuilder.UpdateData(
                table: "NotificationTypes",
                keyColumn: "Id",
                keyValue: 3,
                column: "Name",
                value: "Visited Event Change");
        }
    }
}
