// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventsExpress.Db.Migrations
{
    public partial class RemovedUnusedNotificationTemplates : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 10);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 11);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 12);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "For confirm your email please follow the <a href='{{EmailLink}}'>link</a>", "EventExpress registration", "RegisterVerification" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, congratulations, your account was Unblocked, so you can come back and enjoy spending your time in EventsExpress", "Your account was Unblocked", "UnblockedUser" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, your <a href='{{EventLink}}'>event</a> has been changed.", "Your event was changed", "OwnEventChanged" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, your joined <a href='{{EventLink}}'>event</a> has been changed.", "Joined event was changed", "JoinedEventChanged" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, the event you have been joined was CANCELED. The reason is: {{Reason}} \"<a href='{{EventLink}}'>{{Title}}</a>\"", "The event you have been joined was canceled", "EventStatusCanceled" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, the event you have been joined was BLOCKED. The reason is: {{Reason}} \"<a href='{{EventLink}}'>{{Title}}</a>\"", "The event you have been joined was blocked", "EventStatusBlocked" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, the event you have been joined was ACTIVATED. The reason is: {{Reason}} \"<a href='{{EventLink}}'>{{Title}}</a>\"", "The event you have been joined was activated", "EventStatusActivated" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "Message", "Subject", "Title" },
                values: new object[] { "Dear {{UserEmail}}, you have been approved to join to this event. To check it, please, visit \"<a href='{{EventLink}}'>EventExpress</a>\"", "Approving participation", "ParticipationApproved" });

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "Message", "Subject", "Title" },
                values: new object[,]
                {
                    { 3, "The <a href='{{EventLink}}'>event</a> was created which could interested you.", "New event for you!", "EventCreated" },
                    { 8, "Dear {{UserEmail}}, you have been denied to join to this event. To check it, please, visit \"<a href='{{EventLink}}'>EventExpress</a>\"", "Denying participation", "ParticipationDenied" },
                    { 9, "For confirm your email please follow the <a href='{{EmailLink}}'>link</a>", "EventExpress registration", "RegisterVerification" },
                    { 10, "Dear {{UserEmail}}, congratulations, your account was Unblocked, so you can come back and enjoy spending your time in EventsExpress", "Your account was Unblocked", "UnblockedUser" },
                    { 11, "Dear {{UserEmail}}, your <a href='{{EventLink}}'>event</a> has been changed.", "Your event was changed", "OwnEventChanged" },
                    { 12, "Dear {{UserEmail}}, your joined <a href='{{EventLink}}'>event</a> has been changed.", "Joined event was changed", "JoinedEventChanged" }
                });
        }
    }
}
